# -*- coding: utf-8 -*-
"""Predictive_maintenance_pyspark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_wAZYI1qKr3UiH7BmiU7BiSqAXyJdbD
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

df=pd.read_csv('/content/predictive_maintenance.csv')

df.head()

df=df.drop(columns=['Type','UDI','Product ID'])

y=df['Failure Type']
x=df.drop(columns=['Failure Type'])

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

clf=RandomForestClassifier(random_state=42)

clf.fit(X_train,Y_train)

y_pred=clf.predict(X_test)

accuracy=accuracy_score(Y_test,y_pred)
report=classification_report(Y_test,y_pred)
print(f"Accuracy: {accuracy}")
print("Report:\n",report)

